import React, { useEffect, useMemo, useState } from 'react';
import { AlertTriangle, CalendarClock, Search } from 'lucide-react';
import { WorkshopService } from '../types';
import { api } from '../services/api';

const dayDiff = (due?: string) => due ? Math.floor((new Date(due).setHours(0, 0, 0, 0) - new Date().setHours(0, 0, 0, 0)) / 86_400_000) : null;
const remaining = (service: WorkshopService) => Math.max(0, service.totalAmount - (service.payments || []).reduce((sum, payment) => sum + payment.amount, service.paymentStatus === 'Paid' ? service.totalAmount : 0));

export const ReceivablesView: React.FC<{ onSelect: (id: string) => void }> = ({ onSelect }) => {
  const [services, setServices] = useState<WorkshopService[]>([]); const [search, setSearch] = useState(''); const [loading, setLoading] = useState(false);
  const load = async () => { setLoading(true); try { const result = await api.getReceivables({ search }); setServices(result.data); } finally { setLoading(false); } };
  useEffect(() => { const timer = window.setTimeout(() => void load(), 300); return () => window.clearTimeout(timer); }, [search]);
  const summary = useMemo(() => services.reduce((acc, service) => { const due = dayDiff(service.paymentDueDate); const amount = remaining(service); acc.total += amount; if (due !== null && due < 0) { acc.overdue += amount; acc.count += 1; } return acc; }, { total: 0, overdue: 0, count: 0 }), [services]);
  return <div className="space-y-5"><div className="bg-white border border-slate-100 rounded-3xl p-5"><div className="flex items-start justify-between gap-3"><div><h2 className="font-black text-slate-900">Piutang Pelanggan</h2><p className="text-xs text-slate-500 mt-1">Pantau pembayaran tertunda, jatuh tempo, dan keterlambatan.</p></div><CalendarClock className="w-6 h-6 text-amber-500"/></div><div className="grid grid-cols-2 gap-3 mt-4"><div className="rounded-2xl bg-amber-50 p-3"><p className="text-[10px] font-black text-amber-700">TOTAL PIUTANG</p><p className="font-black text-amber-900">Rp {summary.total.toLocaleString('id-ID')}</p></div><div className="rounded-2xl bg-rose-50 p-3"><p className="text-[10px] font-black text-rose-700">TERLAMBAT ({summary.count})</p><p className="font-black text-rose-900">Rp {summary.overdue.toLocaleString('id-ID')}</p></div></div></div><div className="relative"><Search className="absolute left-4 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-400"/><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Cari nama atau nomor polisi..." className="w-full h-12 rounded-2xl border border-slate-100 bg-white pl-12 pr-4 text-sm font-bold"/></div><div className="space-y-3">{services.map(service => { const due = dayDiff(service.paymentDueDate); const amount = remaining(service); const label = due === null ? 'Belum ada jatuh tempo' : due < 0 ? `Terlambat ${Math.abs(due)} hari` : due === 0 ? 'Jatuh tempo hari ini' : `Jatuh tempo ${due} hari lagi`; const tone = due !== null && due < 0 ? 'border-rose-200 bg-rose-50' : due === 0 ? 'border-amber-200 bg-amber-50' : 'border-slate-100 bg-white'; return <button key={service.id} onClick={() => onSelect(service.id)} className={`w-full text-left rounded-2xl border p-4 ${tone}`}><div className="flex justify-between gap-3"><div><p className="font-black text-slate-900">{service.customerName}</p><p className="text-xs font-mono text-slate-500">{service.vehiclePlate} · {service.vehicleModel}</p><p className="mt-2 text-[10px] font-black uppercase text-slate-600 flex items-center gap-1">{due !== null && due <= 0 && <AlertTriangle className="w-3.5 h-3.5"/>}{label}{service.paymentDueDate ? ` · ${new Date(service.paymentDueDate).toLocaleDateString('id-ID')}` : ''}</p></div><div className="text-right"><p className="text-[10px] font-bold text-slate-500">SISA TAGIHAN</p><p className="font-black text-rose-700">Rp {amount.toLocaleString('id-ID')}</p></div></div></button>; })}{!loading && services.length === 0 && <div className="rounded-2xl bg-white p-10 text-center text-xs font-bold text-slate-400">Tidak ada piutang aktif.</div>}{loading && <p className="text-center text-xs text-slate-400">Memuat piutang…</p>}</div></div>;
};
