-- Baseline schema for a clean PostgreSQL database.  Later migrations evolve this
-- schema; do not edit this file after it has been deployed.
CREATE TABLE "CompanySettings" (
  "id" TEXT NOT NULL DEFAULT 'settings-default', "name" TEXT NOT NULL DEFAULT 'BengkelPro Mandiri', "logoUrl" TEXT,
  "slogan" TEXT NOT NULL DEFAULT 'Solusi Perawatan & Servis Terpercaya', "address" TEXT NOT NULL DEFAULT 'Jl. Otomotif Raya No. 123, Blok B4, Jakarta Selatan',
  "phone" TEXT NOT NULL DEFAULT '0812-3456-7890', "email" TEXT DEFAULT 'kontak@bengkelpro.com', "operationalHours" TEXT DEFAULT 'Senin - Sabtu: 08:00 - 17:00 WIB',
  "ownerName" TEXT DEFAULT 'Pemilik Bengkel', "picName" TEXT DEFAULT 'Rian Herlambang', "defaultMechanicBonusPercent" DOUBLE PRECISION NOT NULL DEFAULT 15,
  "defaultAbsencePenalty" DOUBLE PRECISION NOT NULL DEFAULT 50000, "defaultWarrantyPenalty" DOUBLE PRECISION NOT NULL DEFAULT 75000,
  "allowCustomBonusPerTransaction" BOOLEAN NOT NULL DEFAULT true, "receiptHeader" TEXT DEFAULT 'NOTA RESMI & RINCIAN SERVIS',
  "footerNote" TEXT NOT NULL DEFAULT 'Barang yang sudah dibeli tidak dapat ditukar kecuali perjanjian. Terima kasih atas kepercayaan Anda merawat kendaraan bersama kami.',
  "warrantyTerms" TEXT NOT NULL DEFAULT 'Garansi servis 7 hari atau 500 KM untuk pengerjaan perbaikan yang sama dengan menunjukkan nota ini.',
  "showMechanicOnReceipt" BOOLEAN NOT NULL DEFAULT true, "showWarrantyOnReceipt" BOOLEAN NOT NULL DEFAULT true, "showOdometerOnReceipt" BOOLEAN NOT NULL DEFAULT true,
  "showCustomerPhoneOnReceipt" BOOLEAN NOT NULL DEFAULT true, "receiptContactHelp" TEXT DEFAULT 'WhatsApp CS: 0812-3456-7890',
  "loyaltySilverVisits" INTEGER DEFAULT 3, "loyaltyGoldVisits" INTEGER DEFAULT 6, "loyaltyVipVisits" INTEGER DEFAULT 10,
  "loyaltySilverDiscountPercent" DOUBLE PRECISION DEFAULT 5, "loyaltyGoldDiscountPercent" DOUBLE PRECISION DEFAULT 10, "loyaltyVipDiscountPercent" DOUBLE PRECISION DEFAULT 15,
  "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "CompanySettings_pkey" PRIMARY KEY ("id")
);
CREATE TABLE "User" (
  "id" TEXT NOT NULL, "name" TEXT NOT NULL, "role" TEXT NOT NULL DEFAULT 'Admin', "email" TEXT NOT NULL, "password" TEXT NOT NULL DEFAULT 'akundemo',
  "workshopName" TEXT NOT NULL DEFAULT 'BengkelPro Mandiri', "status" TEXT NOT NULL DEFAULT 'Active', "shifts" TEXT DEFAULT 'Pagi',
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "User_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "User_email_key" ON "User"("email");
CREATE TABLE "Customer" (
  "id" TEXT NOT NULL, "name" TEXT NOT NULL, "phone" TEXT NOT NULL, "totalServiceCount" INTEGER NOT NULL DEFAULT 0, "totalSpent" DOUBLE PRECISION NOT NULL DEFAULT 0,
  "lastVisitDate" TIMESTAMP(3), "loyaltyTier" TEXT DEFAULT 'Bronze', "notes" TEXT, "version" INTEGER NOT NULL DEFAULT 1,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Customer_pkey" PRIMARY KEY ("id")
);
CREATE TABLE "Supplier" (
  "id" TEXT NOT NULL, "name" TEXT NOT NULL, "contact" TEXT NOT NULL, "address" TEXT NOT NULL,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "Supplier_pkey" PRIMARY KEY ("id")
);
CREATE TABLE "Mechanic" (
  "id" TEXT NOT NULL, "name" TEXT NOT NULL, "phone" TEXT NOT NULL, "specialty" TEXT NOT NULL, "status" TEXT NOT NULL DEFAULT 'Active',
  "defaultBonusPercent" DOUBLE PRECISION NOT NULL DEFAULT 15, "dailySalary" DOUBLE PRECISION NOT NULL DEFAULT 100000,
  "warrantyPenaltyAmount" DOUBLE PRECISION NOT NULL DEFAULT 75000, "absencePenaltyAmount" DOUBLE PRECISION NOT NULL DEFAULT 50000,
  "joinedAt" TEXT NOT NULL DEFAULT '2024-01-10', "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "Mechanic_pkey" PRIMARY KEY ("id")
);
CREATE TABLE "SparePart" (
  "id" TEXT NOT NULL, "sku" TEXT, "barcode" TEXT, "name" TEXT NOT NULL, "category" TEXT NOT NULL, "price" DOUBLE PRECISION NOT NULL,
  "purchasePrice" DOUBLE PRECISION NOT NULL DEFAULT 0, "stock" INTEGER NOT NULL DEFAULT 0, "minStock" INTEGER NOT NULL DEFAULT 5, "supplierId" TEXT,
  "imageUrl" TEXT, "rackCode" TEXT, "shelfLevel" TEXT, "binNumber" TEXT, "rackLocation" TEXT, "rackZone" TEXT, "locationNotes" TEXT,
  "version" INTEGER NOT NULL DEFAULT 1, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "SparePart_pkey" PRIMARY KEY ("id"), CONSTRAINT "SparePart_supplierId_fkey" FOREIGN KEY ("supplierId") REFERENCES "Supplier"("id") ON DELETE SET NULL ON UPDATE CASCADE
);
CREATE UNIQUE INDEX "SparePart_sku_key" ON "SparePart"("sku");
CREATE TABLE "Vehicle" (
  "id" TEXT NOT NULL, "customerId" TEXT NOT NULL, "plateNumber" TEXT NOT NULL, "model" TEXT NOT NULL, "brand" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "Vehicle_pkey" PRIMARY KEY ("id"), CONSTRAINT "Vehicle_customerId_fkey" FOREIGN KEY ("customerId") REFERENCES "Customer"("id") ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE "WorkshopService" (
  "id" TEXT NOT NULL, "customerId" TEXT, "customerName" TEXT NOT NULL, "customerPhone" TEXT, "vehicleId" TEXT, "vehiclePlate" TEXT NOT NULL, "vehicleModel" TEXT NOT NULL,
  "kilometers" INTEGER NOT NULL DEFAULT 0, "complaint" TEXT NOT NULL, "diagnosis" TEXT, "status" TEXT NOT NULL DEFAULT 'In Progress',
  "laborFee" DOUBLE PRECISION NOT NULL DEFAULT 0, "totalAmount" DOUBLE PRECISION NOT NULL DEFAULT 0, "paymentStatus" TEXT NOT NULL DEFAULT 'Unpaid', "discountAmount" DOUBLE PRECISION DEFAULT 0,
  "discountReason" TEXT, "mechanicId" TEXT, "mechanicName" TEXT, "mechanicBonusPercent" DOUBLE PRECISION DEFAULT 0, "mechanicBonusAmount" DOUBLE PRECISION DEFAULT 0,
  "hasWarrantyClaim" BOOLEAN NOT NULL DEFAULT false, "warrantyClaimDate" TIMESTAMP(3), "warrantyClaimReason" TEXT, "isMechanicAbsentOnClaim" BOOLEAN DEFAULT false,
  "warrantyDeductionAmount" DOUBLE PRECISION DEFAULT 0, "version" INTEGER NOT NULL DEFAULT 1, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "WorkshopService_pkey" PRIMARY KEY ("id"), CONSTRAINT "WorkshopService_customerId_fkey" FOREIGN KEY ("customerId") REFERENCES "Customer"("id") ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT "WorkshopService_vehicleId_fkey" FOREIGN KEY ("vehicleId") REFERENCES "Vehicle"("id") ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT "WorkshopService_mechanicId_fkey" FOREIGN KEY ("mechanicId") REFERENCES "Mechanic"("id") ON DELETE SET NULL ON UPDATE CASCADE
);
CREATE TABLE "ServicePartItem" (
  "id" TEXT NOT NULL, "serviceId" TEXT NOT NULL, "partId" TEXT NOT NULL, "name" TEXT NOT NULL, "quantity" INTEGER NOT NULL DEFAULT 1, "priceAtTime" DOUBLE PRECISION NOT NULL,
  CONSTRAINT "ServicePartItem_pkey" PRIMARY KEY ("id"), CONSTRAINT "ServicePartItem_serviceId_fkey" FOREIGN KEY ("serviceId") REFERENCES "WorkshopService"("id") ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT "ServicePartItem_partId_fkey" FOREIGN KEY ("partId") REFERENCES "SparePart"("id") ON DELETE RESTRICT ON UPDATE CASCADE
);
CREATE TABLE "MechanicDeduction" (
  "id" TEXT NOT NULL, "mechanicId" TEXT NOT NULL, "mechanicName" TEXT NOT NULL, "serviceId" TEXT, "vehiclePlate" TEXT, "date" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "reason" TEXT NOT NULL, "type" TEXT NOT NULL DEFAULT 'Warranty_Complaint', "amount" DOUBLE PRECISION NOT NULL, "isAbsentNextDay" BOOLEAN NOT NULL DEFAULT false,
  CONSTRAINT "MechanicDeduction_pkey" PRIMARY KEY ("id"), CONSTRAINT "MechanicDeduction_mechanicId_fkey" FOREIGN KEY ("mechanicId") REFERENCES "Mechanic"("id") ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE "MechanicAttendance" (
  "id" TEXT NOT NULL, "mechanicId" TEXT NOT NULL, "date" TEXT NOT NULL, "status" TEXT NOT NULL DEFAULT 'Present', "notes" TEXT,
  CONSTRAINT "MechanicAttendance_pkey" PRIMARY KEY ("id"), CONSTRAINT "MechanicAttendance_mechanicId_fkey" FOREIGN KEY ("mechanicId") REFERENCES "Mechanic"("id") ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE TABLE "PurchaseRecord" (
  "id" TEXT NOT NULL, "partId" TEXT NOT NULL, "supplierId" TEXT NOT NULL, "quantity" INTEGER NOT NULL, "costPrice" DOUBLE PRECISION NOT NULL, "date" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "PurchaseRecord_pkey" PRIMARY KEY ("id"), CONSTRAINT "PurchaseRecord_partId_fkey" FOREIGN KEY ("partId") REFERENCES "SparePart"("id") ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT "PurchaseRecord_supplierId_fkey" FOREIGN KEY ("supplierId") REFERENCES "Supplier"("id") ON DELETE RESTRICT ON UPDATE CASCADE
);
CREATE TABLE "Expense" (
  "id" TEXT NOT NULL, "category" TEXT NOT NULL, "amount" DOUBLE PRECISION NOT NULL, "note" TEXT NOT NULL, "date" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "Expense_pkey" PRIMARY KEY ("id")
);
CREATE TABLE "StockHistory" (
  "id" TEXT NOT NULL, "partId" TEXT NOT NULL, "partName" TEXT NOT NULL, "amount" INTEGER NOT NULL, "type" TEXT NOT NULL, "reason" TEXT NOT NULL, "date" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "StockHistory_pkey" PRIMARY KEY ("id"), CONSTRAINT "StockHistory_partId_fkey" FOREIGN KEY ("partId") REFERENCES "SparePart"("id") ON DELETE RESTRICT ON UPDATE CASCADE
);
CREATE TABLE "DistributorInvoice" (
  "id" TEXT NOT NULL, "invoiceNumber" TEXT NOT NULL, "supplierId" TEXT, "supplierName" TEXT NOT NULL, "branchName" TEXT NOT NULL DEFAULT 'Bengkel Pusat', "branchType" TEXT NOT NULL DEFAULT 'Pusat',
  "totalAmount" DOUBLE PRECISION NOT NULL, "paidAmount" DOUBLE PRECISION NOT NULL DEFAULT 0, "remainingAmount" DOUBLE PRECISION NOT NULL, "version" INTEGER NOT NULL DEFAULT 1, "issueDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "dueDate" TIMESTAMP(3) NOT NULL, "status" TEXT NOT NULL DEFAULT 'Unpaid', "paymentMethod" TEXT DEFAULT 'Transfer', "notes" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "DistributorInvoice_pkey" PRIMARY KEY ("id"), CONSTRAINT "DistributorInvoice_supplierId_fkey" FOREIGN KEY ("supplierId") REFERENCES "Supplier"("id") ON DELETE SET NULL ON UPDATE CASCADE
);
CREATE UNIQUE INDEX "DistributorInvoice_invoiceNumber_key" ON "DistributorInvoice"("invoiceNumber");
CREATE INDEX "DistributorInvoice_dueDate_idx" ON "DistributorInvoice"("dueDate"); CREATE INDEX "DistributorInvoice_branchName_idx" ON "DistributorInvoice"("branchName"); CREATE INDEX "DistributorInvoice_status_idx" ON "DistributorInvoice"("status"); CREATE INDEX "DistributorInvoice_supplierId_idx" ON "DistributorInvoice"("supplierId");
CREATE TABLE "DistributorInvoiceItem" (
  "id" TEXT NOT NULL, "invoiceId" TEXT NOT NULL, "partId" TEXT, "partName" TEXT NOT NULL, "quantity" INTEGER NOT NULL DEFAULT 1, "unitPrice" DOUBLE PRECISION NOT NULL, "totalPrice" DOUBLE PRECISION NOT NULL,
  CONSTRAINT "DistributorInvoiceItem_pkey" PRIMARY KEY ("id"), CONSTRAINT "DistributorInvoiceItem_invoiceId_fkey" FOREIGN KEY ("invoiceId") REFERENCES "DistributorInvoice"("id") ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT "DistributorInvoiceItem_partId_fkey" FOREIGN KEY ("partId") REFERENCES "SparePart"("id") ON DELETE SET NULL ON UPDATE CASCADE
);
CREATE INDEX "DistributorInvoiceItem_invoiceId_idx" ON "DistributorInvoiceItem"("invoiceId"); CREATE INDEX "DistributorInvoiceItem_partId_idx" ON "DistributorInvoiceItem"("partId");
CREATE TABLE "DistributorPayment" (
  "id" TEXT NOT NULL, "invoiceId" TEXT NOT NULL, "amount" DOUBLE PRECISION NOT NULL, "paymentDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "paymentMethod" TEXT NOT NULL DEFAULT 'Transfer', "referenceNo" TEXT, "notes" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "DistributorPayment_pkey" PRIMARY KEY ("id"), CONSTRAINT "DistributorPayment_invoiceId_fkey" FOREIGN KEY ("invoiceId") REFERENCES "DistributorInvoice"("id") ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE INDEX "DistributorPayment_invoiceId_idx" ON "DistributorPayment"("invoiceId");
CREATE TABLE "IdempotencyRecord" (
  "id" TEXT NOT NULL, "key" TEXT NOT NULL, "path" TEXT NOT NULL, "statusCode" INTEGER NOT NULL, "response" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "IdempotencyRecord_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "IdempotencyRecord_key_key" ON "IdempotencyRecord"("key"); CREATE INDEX "IdempotencyRecord_key_idx" ON "IdempotencyRecord"("key");
