import { SparePart } from './types';

export const INITIAL_PARTS: SparePart[] = [
  { 
    id: 'P001', 
    sku: 'OLI-001',
    barcode: '899123450011',
    name: 'Oli Mesin 1L MPX2', 
    price: 95000, 
    purchasePrice: 75000, 
    stock: 24, 
    minStock: 10, 
    category: 'Oli', 
    rackCode: 'Rak A',
    shelfLevel: 'Tingkat 1 (Bawah)',
    binNumber: 'Kotak 01',
    rackZone: 'Gudang Utama',
    locationNotes: 'Deretan botol pelumas matic sebelah kiri',
    lastUpdated: new Date().toISOString() 
  },
  { 
    id: 'P002', 
    sku: 'REM-001',
    barcode: '899123450022',
    name: 'Kampas Rem Depan Cakram', 
    price: 150000, 
    purchasePrice: 110000, 
    stock: 8, 
    minStock: 5, 
    category: 'Rem', 
    rackCode: 'Rak B',
    shelfLevel: 'Tingkat 2 (Tengah)',
    binNumber: 'Kotak 03',
    rackZone: 'Gudang Utama',
    locationNotes: 'Dus merah sistem pengereman Vario/Beat',
    lastUpdated: new Date().toISOString() 
  },
  { 
    id: 'P003', 
    sku: 'FLT-001',
    barcode: '899123450033',
    name: 'Filter Udara Vario 150', 
    price: 65000, 
    purchasePrice: 45000, 
    stock: 15, 
    minStock: 5, 
    category: 'Filter', 
    rackCode: 'Rak C',
    shelfLevel: 'Tingkat 3 (Atas)',
    binNumber: 'Kotak 02',
    rackZone: 'Gudang Utama',
    locationNotes: 'Kotak plastik transparan di ambalan atas',
    lastUpdated: new Date().toISOString() 
  },
  { 
    id: 'P004', 
    sku: 'BSI-001',
    barcode: '899123450044',
    name: 'Busi Iridium CPR9EAIX-9', 
    price: 45000, 
    purchasePrice: 30000, 
    stock: 3, 
    minStock: 10, 
    category: 'Busi', 
    rackCode: 'Etalase Depan',
    shelfLevel: 'Tingkat 1 (Etalase Kaca)',
    binNumber: 'Slot A-05',
    rackZone: 'Toko Kasir',
    locationNotes: 'Etalase kaca depan dekat monitor kasir',
    lastUpdated: new Date().toISOString() 
  },
  { 
    id: 'P005', 
    sku: 'ELK-001',
    barcode: '899123450055',
    name: 'Aki Kering GS Astra GTZ-5S', 
    price: 850000, 
    purchasePrice: 720000, 
    stock: 5, 
    minStock: 2, 
    category: 'Kelistrikan', 
    rackCode: 'Rak D',
    shelfLevel: 'Tingkat 1 (Bawah)',
    binNumber: 'Palet 01',
    rackZone: 'Gudang Utama',
    locationNotes: 'Di lantai palet kayu aman dari kelembaban',
    lastUpdated: new Date().toISOString() 
  },
  { 
    id: 'P006', 
    sku: 'BAN-001',
    barcode: '899123450066',
    name: 'Ban Luar Tubeless 90/90-14 FDR', 
    price: 245000, 
    purchasePrice: 195000, 
    stock: 12, 
    minStock: 4, 
    category: 'Ban', 
    rackCode: 'Gudang Belakang',
    shelfLevel: 'Gantungan Ban Baris 1',
    binNumber: 'Hanger 04',
    rackZone: 'Gudang Belakang',
    locationNotes: 'Tergantung di pipa rak ban belakang',
    lastUpdated: new Date().toISOString() 
  }
];

export const SERVICE_TYPES = [
  'Servis Rutin',
  'Ganti Oli',
  'Tune Up',
  'Perbaikan Mesin',
  'Kelistrikan',
  'Body Repair',
];
